# Generated by Django 4.2.7 on 2023-12-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("DataProcess", "0002_delete_sensor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sensor_id",
                    models.CharField(max_length=100, unique=True, verbose_name="传感器ID"),
                ),
                ("gateway_id", models.CharField(max_length=100, verbose_name="网关ID")),
                ("type", models.CharField(max_length=100, verbose_name="传感器类型")),
                ("user", models.CharField(max_length=100, verbose_name="用户")),
            ],
        ),
    ]
