# Generated by Django 4.2.7 on 2023-12-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sensor_id",
                    models.CharField(max_length=100, unique=True, verbose_name="传感器ID"),
                ),
                ("status", models.BooleanField(default=False, verbose_name="状态")),
            ],
        ),
    ]
