# Generated by Django 4.2.7 on 2023-12-06 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DataProcess", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sensor",
        ),
    ]
