# Generated by Django 4.2.7 on 2023-12-06 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("DataProcess", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="时间")),
                ("attribute", models.CharField(max_length=100, verbose_name="属性")),
                ("value", models.FloatField(verbose_name="值")),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataProcess.sensor",
                        verbose_name="传感器",
                    ),
                ),
            ],
        ),
    ]
